// <auto-generated />
namespace IntegracaoPsP.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_atributte_integration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_atributte_integration));
        
        string IMigrationMetadata.Id
        {
            get { return "201804041239030_new_atributte_integration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
